# Generated by Django 4.2.5 on 2023-10-21 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import src.megano.utils.save_img


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="название")),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="статус",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="api_shop.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="цена",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="кол-во"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время добавления"
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="название")),
                (
                    "short_description",
                    models.CharField(max_length=500, verbose_name="краткое описание"),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="описание"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_shop.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "db_table": "products",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="тег")),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="характеристика"),
                ),
                ("value", models.CharField(max_length=100, verbose_name="значение")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="api_shop.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика товара",
                "verbose_name_plural": "характеристики товаров",
                "db_table": "specifications",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="автор"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="отзыв")),
                (
                    "rate",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api_shop.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "db_table": "reviews",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="api_shop.tag", verbose_name="теги"),
        ),
        migrations.CreateModel(
            name="ImageForProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.ImageField(
                        upload_to=src.megano.utils.save_img.save_img_for_product,
                        verbose_name="изображение",
                    ),
                ),
                ("alt", models.CharField(max_length=250, verbose_name="alt")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api_shop.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
                "db_table": "images_for_products",
            },
        ),
        migrations.CreateModel(
            name="ImageForCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.ImageField(
                        upload_to=src.megano.utils.save_img.save_img_for_category,
                        verbose_name="изображение",
                    ),
                ),
                ("alt", models.CharField(max_length=250, verbose_name="alt")),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="api_shop.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
                "db_table": "images_for_category",
            },
        ),
    ]
