# Generated by Django 4.2.5 on 2023-10-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageforcategory',
            old_name='src',
            new_name='path',
        ),
    ]
