# Generated by Django 4.2.5 on 2023-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
