# Generated by Django 4.2.5 on 2023-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_shop", "0004_alter_product_category_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(
                related_name="categories", to="api_shop.tag", verbose_name="теги"
            ),
        ),
    ]
