# Generated by Django 4.2.5 on 2023-11-05 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_shop", "0007_basket_count_alter_basket_product_alter_basket_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата оформления заказа"
                    ),
                ),
                (
                    "delivery",
                    models.IntegerField(
                        choices=[(1, "Обычная доставка"), (2, "Экспресс доставка")],
                        default=1,
                        verbose_name="тип доставки",
                    ),
                ),
                (
                    "payment",
                    models.IntegerField(
                        choices=[
                            (1, "Онлайн картой"),
                            (2, "Онлайн со случайного чужого счета"),
                        ],
                        default=1,
                        verbose_name="оплата",
                    ),
                ),
                (
                    "total_cost",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="стоимость заказа",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Оформлен"),
                            (2, "Не оплачен"),
                            (3, "Подтверждение оплаты"),
                            (4, "Оплачен"),
                            (5, "Доставляется"),
                        ],
                        default=1,
                        verbose_name="cтатус",
                    ),
                ),
                ("city", models.CharField(max_length=150, verbose_name="город")),
                ("address", models.CharField(max_length=300, verbose_name="адрес")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "db_table": "orders",
                "ordering": ["-data_created"],
            },
        ),
        migrations.CreateModel(
            name="PurchasedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="кол-во")),
                ("price", models.PositiveIntegerField(verbose_name="цена")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api_shop.order",
                        verbose_name="номер заказа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api_shop.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар в заказе",
                "verbose_name_plural": "товары в заказе",
                "db_table": "purchased_products",
            },
        ),
    ]
