# Generated by Django 4.2.5 on 2023-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_shop", "0008_order_purchasedproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.IntegerField(
                choices=[(1, "Обычная доставка"), (2, "Экспресс доставка")],
                null=True,
                verbose_name="тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.IntegerField(
                choices=[
                    (1, "Онлайн картой"),
                    (2, "Онлайн со случайного чужого счета"),
                ],
                null=True,
                verbose_name="оплата",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Оформление"),
                    (2, "Оформлен"),
                    (3, "Не оплачен"),
                    (4, "Подтверждение оплаты"),
                    (5, "Оплачен"),
                    (6, "Доставляется"),
                ],
                null=True,
                verbose_name="cтатус",
            ),
        ),
    ]
