# Generated by Django 4.2.5 on 2023-11-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shop', '0009_remove_order_total_cost_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=150, null=True, verbose_name='город'),
        ),
    ]
